osx_image: xcode7
language: objective-c
xcode_sdk: iphonesimulator9.0

cache:
  - cocoapods
  - bundler

before_install:
	bundle exec pod keys set TheMovieDataBaseApiKey "-" Movieland

install:
  - bundle install --without=documentation
  - gem update fastlane

before_script:
  - export LANG=en_US.UTF-8

script: bundle exec fastlane test