osx_image: xcode7.1
language: objective-c
xcode_sdk: iphonesimulator9.1

cache:
  - cocoapods
  - bundler

install:
  - bundle install --without=documentation
  - gem update fastlane
  - bundle exec pod keys set TheMovieDataBaseApiKey "-" Movieland

before_script:
  - export LANG=en_US.UTF-8

script: bundle exec fastlane test