# Change the syntax highlighting to Ruby
# All lines starting with a # are ignored when running `fastlane`

fastlane_version "1.42.0"

default_platform :ios

APP_WORKSPACE = "Movieland.xcworkspace"
APP_SCHEME = "Movieland"
APP_TEST_SCHEME = "Movieland"

platform :ios do
  before_all do
  end
 
  desc "Runs all the tests"
  lane :test do
    scan(
        workspace: APP_WORKSPACE,
        scheme: APP_TEST_SCHEME,
        open_report: false
      )
  end

  after_all do |lane|
  end

  error do |lane, exception|
  end
end
