# Change the syntax highlighting to Ruby
# All lines starting with a # are ignored when running `fastlane`

default_platform :ios

APP_WORKSPACE = "Movieland.xcworkspace"
APP_SCHEME = "Movieland"
APP_TEST_SCHEME = "MovielandTests"

platform :ios do
  before_all do
  end

  desc "Runs all the tests"
  lane :test do
    scan(
      workspace: APP_WORKSPACE,
      scheme: APP_TEST_SCHEME,
      destination: "name=iPhone 5s,OS=9.1"
    )
  end

  after_all do |lane|
  end

  error do |lane, exception|
  end
end
